### ISSUE TITLE
Fluent dependencies are bundled on Node instead of being added to dependencies

### ISSUE THREAD

**Issue by Loskir** [grammyjs/i18n#29]
<img width="336" alt="image" src="https://user-images.githubusercontent.com/21295738/196927984-31f8f7e4-fa4e-4371-a3ec-eba147d3f0cf.png">

**Comment by dcdunkan** [comment]
Did you mean, we're transforming better_fluent to node instead of using moebius/fluent as the node dependency? If that's the case, it is because the @moebius/fluent package has no synchronous method for adding translations, which i18n uses internally (we had a discussion about it, iirc). better_fluent has sync methods.

**Comment by Loskir** [comment]
We can release better_fluent on npm
My main concern is that if I need to import something from better_fluent I have to import it from some internal thing in i18n. Re-exporting better_fluent more cleanly would also work
