### ISSUE TITLE
Line breaks with HTML parse mode without template variables

### ISSUE THREAD

**Issue by deman4ik** [grammyjs/i18n#7]
Telegram doesn't show line breaks when using `parse_mode: "HTML"` and no template variables passes to template function

en.yaml
```yaml
test: First Line\nSecond Line
test2: First Line\nSecond Line${n}
```

Example Grammy code with and without template variables
```js
await ctx.reply(ctx.i18n.t("test"), { parse_mode: "HTML" });
await ctx.reply(ctx.i18n.t("test2", { n: "" }), { parse_mode: "HTML" });
```

Result in Telegram
<img width="213" alt="Screenshot 2021-09-21 at 13 49 52" src="https://user-images.githubusercontent.com/913027/134161708-bcc42bfe-f56f-4602-8462-0669339bc91e.png">

**Comment by EdJoPaTo** [comment]
I think your problem is unrelated to the `parse_mode`. The yaml format is a bit specific there but after getting used to it its quite nice to use.

When I use multiline things I use the block style. Its relatively well described here: https://yaml-multiline.info/
basically your test would look like this:

```yaml
test: >
  First Line

  Second Line
```

A single new line is normally wrapped and can be used to use one sentence per line for example in the yaml file.
Two new lines in the yaml file results in a "real" new line. Markdown often (not always) uses the same logic for dealing with newlines.

Hope it helps!

**Comment by deman4ik** [comment]
Ok, it helps, thank you.

But why `\n` still works when using template data?

**Comment by EdJoPaTo** [comment]
Yaml itself does not ignore characters, you get exactly what you type. With the variables they get replaced to what you provided via code. That isnt yaml anymore so you get what you are used to in pogramming with TypeScript/JavaScript.

Its basically: yaml → i18n → choose template → apply template data → use with grammY.
Applying the data is a way later step, importing yaml only happens once when you start your bot.

I hope it made it more clear what is happening under the hood here.
